version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: badminton-api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - CORS_ORIGIN=https://badminton.xenocer.com,http://localhost:9009,http://localhost:5173
      - GOOGLE_CLIENT_ID=634347628772-ot3d906un0ar1oq5p3b98tci67l99non.apps.googleusercontent.com
    volumes:
      - ./server/uploads:/app/server/uploads
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: https://badminton-api.xenocer.com
    container_name: badminton-web
    ports:
      - "9009:9009"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - appnet

  # Tunnel #1: Backend hostname -> backend service
cloudflared-be:
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN_BE}
    container_name: cloudflared-badminton-be
    depends_on:
      backend:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Bangkok
    image: cloudflare/cloudflared:latest
    networks:
      appnet: null
    restart: unless-stopped

  cloudflared-fe:
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN_FE}
    container_name: cloudflared-badminton-fe
    depends_on:
      frontend:
        condition: service_started
        required: true
    environment:
      TZ: Asia/Bangkok
    image: cloudflare/cloudflared:latest
    networks:
      appnet: null
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
